# Stage 1: Build the UI (Nuxt.js)
FROM node:20-slim AS ui-builder

# Install pnpm
RUN npm install -g pnpm

WORKDIR /app/ui

# Copy UI project files and install dependencies
COPY ui/package.json ui/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --shamefully-hoist

# Copy the rest of the UI code and build
COPY ui/ ./
RUN pnpm run build

# Stage 2: Build the Java Application
FROM gradle:8.5.0-jdk21 AS java-builder

WORKDIR /app

# Copy the entire project
COPY . .

# Build the Java application and create the distribution
RUN ./gradlew :app:installDist

# Stage 3: Final Image
FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

# Copy Java application from the builder stage
COPY --from=java-builder /app/app/build/install/app ./

# Copy UI build from the ui-builder stage
COPY --from=ui-builder /app/ui/.output/public ./ui

# Copy configuration
COPY config.properties ./

# Expose the load balancer port
EXPOSE 8080

# The run script generated by Gradle will be the entrypoint
CMD ["bin/app", "config.properties"]
