/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  void testAppInitialization() {
    // Simple test to verify the App class can be instantiated
    App app = new App();
    assertNotNull(app, "App should be initialized");
  }
}
